version: "3.9"
services:
  db:
    image: mysql:8.4
    container_name: videoclubdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 53633393S
      MYSQL_DATABASE: videoclub_pro
    volumes:
      - db_data:/var/lib/mysql
      - ./creacion_db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqliadmin ping -proot -h localhost"]
  app:
    build: .
    container_name: ae3-pro
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/videoclub_pro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 53633393S
      SPRING_JPA_HIBERNATE_DLL_AUTO: update
      TZ: Europe/Madrid
volumes:
  db_data: